import m1 from "../images/chair1.jpg";
import m2 from "../images/chair2.jpg";
import m3 from "../images/chair3.webp";
import m10 from "../images/chair10.avif";

export const images_info = [
  {
    img_url: m1,
    uzunlik: "53sm",
    kenglik: "45sm",
    balandlik: "76sm",
    stol_b: "47sm",
    material: "plastmassa",
    ogirlig: "120kg",
    ramka_rangi:'qora',
    olinadigan_qopqoq:'yo`q',
    opsiyasi:'yig`ilmagan',
    asosiy_rang:'oq',
    katlanishi:"yo`q",
    country:'Xitoy'
  },
  {
    img_url: m1,
    uzunlik: "53sm",
    kenglik: "45sm",
    balandlik: "76sm",
    stol_b: "47sm",
    material: "plastmassa",
    ogirlig: "120kg",
    ramka_rangi:'qora',
    olinadigan_qopqoq:'yo`q',
    opsiyasi:'yig`ilmagan',
    asosiy_rang:'oq',
    katlanishi:"yo`q",
    country:'Xitoy'
  },
  {
    img_url: m1,
    uzunlik: "53sm",
    kenglik: "45sm",
    balandlik: "76sm",
    stol_b: "47sm",
    material: "plastmassa",
    ogirlig: "120kg",
    ramka_rangi:'qora',
    olinadigan_qopqoq:'yo`q',
    opsiyasi:'yig`ilmagan',
    asosiy_rang:'oq',
    katlanishi:"yo`q",
    country:'Xitoy'
  },
  {
    img_url: m1,
    uzunlik: "53sm",
    kenglik: "45sm",
    balandlik: "76sm",
    stol_b: "47sm",
    material: "plastmassa",
    ogirlig: "120kg",
    ramka_rangi:'qora',
    olinadigan_qopqoq:'yo`q',
    opsiyasi:'yig`ilmagan',
    asosiy_rang:'oq',
    katlanishi:"yo`q",
    country:'Xitoy'
  },
  {
    img_url: m1,
    uzunlik: "53sm",
    kenglik: "45sm",
    balandlik: "76sm",
    stol_b: "47sm",
    material: "plastmassa",
    ogirlig: "120kg",
    ramka_rangi:'qora',
    olinadigan_qopqoq:'yo`q',
    opsiyasi:'yig`ilmagan',
    asosiy_rang:'oq',
    katlanishi:"yo`q",
    country:'Xitoy'
  },
  {
    img_url: m1,
    uzunlik: "53sm",
    kenglik: "45sm",
    balandlik: "76sm",
    stol_b: "47sm",
    material: "plastmassa",
    ogirlig: "120kg",
    ramka_rangi:'qora',
    olinadigan_qopqoq:'yo`q',
    opsiyasi:'yig`ilmagan',
    asosiy_rang:'oq',
    katlanishi:"yo`q",
    country:'Xitoy'
  },
  {
    img_url: m1,
    uzunlik: "53sm",
    kenglik: "45sm",
    balandlik: "76sm",
    stol_b: "47sm",
    material: "plastmassa",
    ogirlig: "120kg",
    ramka_rangi:'qora',
    olinadigan_qopqoq:'yo`q',
    opsiyasi:'yig`ilmagan',
    asosiy_rang:'oq',
    katlanishi:"yo`q",
    country:'Xitoy'
  },
  {
    img_url: m1,
    uzunlik: "53sm",
    kenglik: "45sm",
    balandlik: "76sm",
    stol_b: "47sm",
    material: "plastmassa",
    ogirlig: "120kg",
    ramka_rangi:'qora',
    olinadigan_qopqoq:'yo`q',
    opsiyasi:'yig`ilmagan',
    asosiy_rang:'oq',
    katlanishi:"yo`q",
    country:'Xitoy'
  },
  {
    img_url: m1,
    uzunlik: "53sm",
    kenglik: "45sm",
    balandlik: "76sm",
    stol_b: "47sm",
    material: "plastmassa",
    ogirlig: "120kg",
    ramka_rangi:'qora',
    olinadigan_qopqoq:'yo`q',
    opsiyasi:'yig`ilmagan',
    asosiy_rang:'oq',
    katlanishi:"yo`q",
    country:'Xitoy'
  },
  {
    img_url: m1,
    uzunlik: "53sm",
    kenglik: "45sm",
    balandlik: "76sm",
    stol_b: "47sm",
    material: "plastmassa",
    ogirlig: "120kg",
    ramka_rangi:'qora',
    olinadigan_qopqoq:'yo`q',
    opsiyasi:'yig`ilmagan',
    asosiy_rang:'oq',
    katlanishi:"yo`q",
    country:'Xitoy'
  },
];
