import m1 from "../images/chair1.jpg";

export const images_info = [
  {
    img_url: m1,
    name:'AA-1012',
    narxi:'1 200 000',
    uzunlik: "53sm",
    kenglik: "45sm",
    balandlik: "76sm",
    stol_b: "47sm",
    material: "plastmassa",
    ogirlig: "120kg",
    ramka_rangi:'qora',
    olinadigan_qopqoq:'yo`q',
    opsiyasi:'yig`ilmagan',
    asosiy_rang:'oq',
    katlanishi:"yo`q",
    country:'Xitoy'
  },
  {
    img_url: m1,
    name:'AA-1012',
    narxi:'1 200 000',
    uzunlik: "53sm",
    kenglik: "45sm",
    balandlik: "76sm",
    stol_b: "47sm",
    material: "plastmassa",
    ogirlig: "120kg",
    ramka_rangi:'qora',
    olinadigan_qopqoq:'yo`q',
    opsiyasi:'yig`ilmagan',
    asosiy_rang:'oq',
    katlanishi:"yo`q",
    country:'Xitoy'
  },
  {
    img_url: m1,
    name:'AA-1012',
    narxi:'1 200 000',
    uzunlik: "53sm",
    kenglik: "45sm",
    balandlik: "76sm",
    stol_b: "47sm",
    material: "plastmassa",
    ogirlig: "120kg",
    ramka_rangi:'qora',
    olinadigan_qopqoq:'yo`q',
    opsiyasi:'yig`ilmagan',
    asosiy_rang:'oq',
    katlanishi:"yo`q",
    country:'Xitoy'
  },
  {
    img_url: m1,
    name:'AA-1012',
    narxi:'1 200 000',
    uzunlik: "53sm",
    kenglik: "45sm",
    balandlik: "76sm",
    stol_b: "47sm",
    material: "plastmassa",
    ogirlig: "120kg",
    ramka_rangi:'qora',
    olinadigan_qopqoq:'yo`q',
    opsiyasi:'yig`ilmagan',
    asosiy_rang:'oq',
    katlanishi:"yo`q",
    country:'Xitoy'
  },
  {
    img_url: m1,
    name:'AA-1012',
    narxi:'1 200 000',
    uzunlik: "53sm",
    kenglik: "45sm",
    balandlik: "76sm",
    stol_b: "47sm",
    material: "plastmassa",
    ogirlig: "120kg",
    ramka_rangi:'qora',
    olinadigan_qopqoq:'yo`q',
    opsiyasi:'yig`ilmagan',
    asosiy_rang:'oq',
    katlanishi:"yo`q",
    country:'Xitoy'
  },
  {
    img_url: m1,
    name:'AA-1012',
    narxi:'1 200 000',
    uzunlik: "53sm",
    kenglik: "45sm",
    balandlik: "76sm",
    stol_b: "47sm",
    material: "plastmassa",
    ogirlig: "120kg",
    ramka_rangi:'qora',
    olinadigan_qopqoq:'yo`q',
    opsiyasi:'yig`ilmagan',
    asosiy_rang:'oq',
    katlanishi:"yo`q",
    country:'Xitoy'
  },
  {
    img_url: m1,
    name:'AA-1012',
    narxi:'1 200 000',
    uzunlik: "53sm",
    kenglik: "45sm",
    balandlik: "76sm",
    stol_b: "47sm",
    material: "plastmassa",
    ogirlig: "120kg",
    ramka_rangi:'qora',
    olinadigan_qopqoq:'yo`q',
    opsiyasi:'yig`ilmagan',
    asosiy_rang:'oq',
    katlanishi:"yo`q",
    country:'Xitoy'
  },
  {
    img_url: m1,
    name:'AA-1012',
    narxi:'1 200 000',
    uzunlik: "53sm",
    kenglik: "45sm",
    balandlik: "76sm",
    stol_b: "47sm",
    material: "plastmassa",
    ogirlig: "120kg",
    ramka_rangi:'qora',
    olinadigan_qopqoq:'yo`q',
    opsiyasi:'yig`ilmagan',
    asosiy_rang:'oq',
    katlanishi:"yo`q",
    country:'Xitoy'
  },
  {
    img_url: m1,
    name:'AA-1012',
    narxi:'1 200 000',
    uzunlik: "53sm",
    kenglik: "45sm",
    balandlik: "76sm",
    stol_b: "47sm",
    material: "plastmassa",
    ogirlig: "120kg",
    ramka_rangi:'qora',
    olinadigan_qopqoq:'yo`q',
    opsiyasi:'yig`ilmagan',
    asosiy_rang:'oq',
    katlanishi:"yo`q",
    country:'Xitoy'
  },
  {
    img_url: m1,
    name:'AA-1012',
    narxi:'1 200 000',
    uzunlik: "53sm",
    kenglik: "45sm",
    balandlik: "76sm",
    stol_b: "47sm",
    material: "plastmassa",
    ogirlig: "120kg",
    ramka_rangi:'qora',
    olinadigan_qopqoq:'yo`q',
    opsiyasi:'yig`ilmagan',
    asosiy_rang:'oq',
    katlanishi:"yo`q",
    country:'Xitoy'
  },
];

export const products_slider =[
  [
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
  ],
  [
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
  ],
  [
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
    {
      img_url: m1,
      name:'AA-1012',
      narxi:'1 200 000',
      uzunlik: "53sm",
      kenglik: "45sm",
      balandlik: "76sm",
      stol_b: "47sm",
      material: "plastmassa",
      ogirlig: "120kg",
      ramka_rangi:'qora',
      olinadigan_qopqoq:'yo`q',
      opsiyasi:'yig`ilmagan',
      asosiy_rang:'oq',
      katlanishi:"yo`q",
      country:'Xitoy'
    },
  ]
]